### ISSUE TITLE
Playback doesn't move

### ISSUE THREAD

**Issue by evhumphrey** [tungeric/SoundCrown#9]
On user's profile page, the play bar (seek) for that track doesn't move with the song (the continuous playbar seek does move, which is awesome!)

**Comment by tungeric** [comment]
I'm aware of this issue... it's a little difficult to pass that amount of data back and forth between the two components. What I should have done is make the individual play bars a single component, and the play bar and the user/track pages would both just use the same component, but alas I didn't think that far. Will have to see if I have time to fix this later this week.

**Comment by tungeric** [comment]
I made a workaround - it's just an animation when I hit play now :D
